### ISSUE TITLE
Any filename collisions?

### ISSUE THREAD

**Issue by damithc** [Parcly-Taxel/fetcher#1]
Does the script detect possible filename collisions? i.e., multiple files with the same name.

**Comment by Parcly-Taxel** [comment]
Currently I am copying files one at a time. As such, after the first instance of a filename is transferred, subsequent instances of the same filename from other repositories are _not_ transferred, and are caught by `transfer_files()`:

https://github.com/Parcly-Taxel/FETcher/blob/4848cd5d951577a4b170db53dc56fd9b5e0b7fce/fetcher/fetch.py#L44-L55

These collisions are printed out after the entire transfer is completed; if you want the collisions to be displayed in another place, however, I am open to that.

**Comment by damithc** [comment]
I see. Were there any filename collisions for the test run done on the recent CS2103 batch?

**Comment by Parcly-Taxel** [comment]
> I see. Were there any filename collisions for the test run done on the recent CS2103 batch?

There were no collisions. The use of UUIDs for filenames, for all practical purposes, eliminates this problem.

**Comment by damithc** [comment]
Nice. This becomes a non-issue in that case. We'll leave the code that detects name collisions but no need to actually handle such collisions.
