### ISSUE TITLE
Explore if threads can speed up the throughput

### ISSUE THREAD

**Issue by damithc** [Parcly-Taxel/fetcher#2]
15 minutes for 300 repos is already good enough.
However, you can explore if there are significant gains to be had by using parallel threads, given that file downloading is heavily IO bound. Perhaps you can try it as a separate branch to evaluate gains vs cost (in terms of additional code complexity).

**Comment by Parcly-Taxel** [comment]
@damithc After using [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) to parallelise the repository downloads, the total time taken for the CS2103/T AY1920S1 cohort **fell by 60%**, from ~15 minutes to ~6 minutes on my 4-core computer. I did some other tasks while the improved program was running.

**Comment by damithc** [comment]
Nice!
